;============================================================================;
;========================== USEFULL DEFINES =================================;
;============================================================================;

; BIOS interrupts
BIOS_INT_VIDEO          equ 0x10
BIOS_INT_DRIVE          equ 0x13

; define usefull characters
CHAR_NULL           equ 0x0
CHAR_LF             equ 0xa
CHAR_CR             equ 0xd

